sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
linkReplacements:
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.32.0"
    - "7.1.30"
