sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
linkReplacements:
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: false
  exasolDbVersions:
    - "7.1.25"
    - "8.24.0"
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
