name: CI Build with Java 8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  java-8-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            8
            17
          cache: "maven"
      - name: Run maven compile with Java 8
        run: mvn --batch-mode -Djava.version=8 clean compile
