name: Prepare AWS Marketplace Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Install xmlstarlet
        run: sudo apt install -y --no-install-recommends xmlstarlet
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MARKETPLACE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MARKETPLACE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Push connector image to AWS Marketplace repository
        run: ./tools/pushDockerImageToECR.sh
        env:
          AWS_REGION: us-east-1
          MARKETPLACE_ECR_REPO_NAME: ${{ secrets.MARKETPLACE_ECR_REPO_NAME }}
          MARKETPLACE_ECR_ACCOUNT_ID: ${{ secrets.MARKETPLACE_ECR_ACCOUNT_ID }}
      - name: Clean up
        run: rm -rf Dockerfile artifacts/
      - name: Create issue for publishing new version manually
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
